title: PianopianoAI
description: Capire l'intelligenza artificiale, piano piano.

url: "https://stebash.github.io"
baseurl: "/pianopianoai-site"

markdown: kramdown
permalink: /articoli/:title/

collections:
  posts:
    output: true
